### ISSUE TITLE
Node label obscures dragging.

### ISSUE THREAD

**Issue by GeoffGodwin** [vasturiano/react-force-graph#16]
I've noticed that in the 2D graph, the hover label is centered directly on the mouse so it prevents the mouse from being able to directly drag the node.

I believe it's caused by the following CSS:

```css
.graph-tooltip {
    ...
    transform: translate(-50%, 25px);
    ...
}
```

In my project I overwrote this by changing the 25px to 15px.

Thoughts?
